### ISSUE TITLE
Question - Showing the notifications in app, when user sign-in.

### ISSUE THREAD

**Issue by jpatel3** [pinax/pinax-notifications#24]
Thanks for providing this app. It seems very useful. After reading the functionality at various places (e.g. stack overflow, and few blogs), I included this app to show the notifications in the app (not via email.) However, I don't see any documentation to do the same. 

Can someone please provide comment on it? Is it possible with this app, or the 4 points from documentation are outdated?
https://django-notification.readthedocs.org/en/latest/index.html#welcome-to-django-notification-s-documentation

**Comment by MiltonLn** [comment]
I have the same question, thanks.

**Comment by evilplanet** [comment]
Me, too.

**Comment by grahamu** [comment]
After comparing old code models with current code, I believe a decision was made to _not_ define a generic "Notice" model but let each backend decide how a notification is handled.

In the default backend, an email is constructed and sent to recipients, but no notification "instance" is saved. It's a simple system by design.

If you desire the ability to show unread notifications on your site, I suppose you would build a different backend, perhaps inheriting from [`EmailBackend`](https://github.com/pinax/pinax-notifications/blob/master/pinax/notifications/backends/email.py#L9). You would need to save the notification data (during processing in `<backend>.deliver()` method) as an instance of your own Django notification model, defined in your project. In order to show unread notifications you'd need to provide your own template tags (for example) returning the desired notification instances. Seems like you'd need a view to display a notification. At some point when a user (of perhaps many notified users) views a notification you'd need to save that fact, likely with a different model associating user with notification, to indicate the notification was viewed by a specific user. Something along those lines.

This functionality gets complicated quickly, so pinax-notifications provides the flexibility of defining your own backend, to suit your needs, rather than constraining the concept of a notification.

Ref issue #19.
