### ISSUE TITLE
Migration error when used with condottieri_notification

### ISSUE THREAD

**Issue by evilplanet** [pinax/pinax-notifications#80]
`condottieri_notification` app migration file 0001_initial dependencies reference nonexistent parent node ('pinax_notifications', '0002_auto_20180118_0138')

Any ideas?

```
raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration condottieri_notification.0001_initial dependencies reference nonexistent parent node ('pinax_notifications', '0002_auto_20180118_0138')
```

**Comment by grahamu** [comment]
@evilplanet from your report it appears `condottieri_notification` is referencing an non-existent `pinax-notifications` migration. There have not been any migrations added to pinax-notifications since 2017-October-03, so something is wrong in that `condottieri_notification` migration.

The correct pinax-notifications migration reference is `('pinax_notifications', '0002_auto_20171003_2006')`.

Let us know how you make out.

**Comment by evilplanet** [comment]
I deleted all migrations files and re-generated them using `makemigrations`, this time I see `('pinax_notifications', '0003_auto_20180121_0216')`. I can run `migrate` locally, no error. But when I push it to heroku and then try to migrate, the same issue occurs.

When I changed it into `('pinax_notifications', '0002_auto_20171003_2006')`. It still says `django.db.migrations.exceptions.NodeNotFoundError`.

**Comment by evilplanet** [comment]
It seems that I was using version 4.0.0, which does not have that migration, yet. I upgraded to 4.1.0, the issue disappears.

**Comment by paltman** [comment]
You shouldn’t delete migrations in pinax-notifications.

**Comment by evilplanet** [comment]
I just ran the following commands in the project repo:
```
find . -path "*/migrations/*.py" -not -name "__init__.py" -delete
find . -path "*/migrations/*.pyc"  -delete
```
I think I didn't delete `pinax-notifications`' migrations, since I installed it via pip (thus the migration files are not in the project repo). Or did I?
